### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by LorenzoPapi**
### Re-did because github is dumb...

### CODE REVIEW

**Comment by necauqua** [comment]
Well you've made a fork and then pushed a commit to the forked master and then made a PR to merge the forked master into my master.
And then you pushed more commits into your forked master, forgetting that it was wired to the PR so you'd need to push your commits to another branch - or, as you shoul've done in the first place, push your initial commit in a new branch and then make a PR with it, so that your master is free to get any commits pushed into.

Also you could've reset the extra commits and force-push your master so it has one commit that you want to merge in again and thus fix the old PR instead of making a new one, but whatever, its fine :)

**Comment by LorenzoPapi** [comment]
Ok thanks for the explanation (I'm a n00b with GitHub), you should merge the request lol

**Comment by LorenzoPapi** [comment]
dump LUL

**Comment by LorenzoPapi** [comment]
<:nyeh:774025716547321896>

**Comment by LorenzoPapi** [comment]
Bump <:nyeh:774025716547321896>

**Comment by necauqua** [comment]
Well big giant commit is up there, gl

**Comment by LorenzoPapi** [comment]
it says you can merge it, go on

**Comment by necauqua** [comment]
Well, first of all:
image

And second, localizations _did change_ a bit, so please rewiew and push/recreate the PR :shrug:

**Comment by LorenzoPapi** [comment]
ah didn't know localization changed, I'll redo the pr

**Pull request closed without merging**
